<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageId>hknt</PackageId>
    <Version>1.0.2</Version>
    <Authors>HK AI Research Team</Authors>
    <Company>HK AI</Company>
    <Description>C# / .NET bindings for HK neural tensor format and SIMD execution.</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
